In [1]:
import pandas as pd
import matplotlib.pyplot as plt

ukr_database = pd.read_csv("data/uadatabase.csv")
ukr_database.head()

,LastName,Patronym,FirstName,DateBirth,Sex,From,Nationality,Unit,TypeUnit,RankG1,RankG2,Rank,DateEvent,LocationEvent,Age,AgeFlag,Status,namefile
0,Abramchuk,Ivanovych,Kostjantyn,7-Aug-81,1.0,Kyiv,Ukraine,Unknown,Unknown,Unknown or no Officer,Unknown or no Officer,Unknown,10-Mar-26,"Hirke, Vozdvyzhivska rural community, Pology D...",44.589554,0,missing,abramchuk-kostjantyn-ivanovych-1981-08-07-kyiv...
1,Abramchuk,Ivanovych,Roman,8-Sep-86,1.0,"Tojkut,Kovelska urban community,Kovel District...",Ukraine,93rd separate mechanized brigade<,Mechanized/Infantry,Unknown or no Officer,Unknown or no Officer,Soldier,15-May-23,"Bakhmut, Bakhmutska urban community, Bakhmut D...",36.682478,0,dead,abramchuk-roman-ivanovych-1986-09-08-36-tojkut...
2,Abramchuk,Oleksandrovych,Artem,18-Oct-87,1.0,"Kovel,Kovelska urban community,Kovel District,...",Ukraine,155th Separate Infantry Brigade<,Mechanized/Infantry,Unknown or no Officer,Unknown or no Officer,Soldier,20-Aug-25,"Pokrovsk, Pokrovska urban community, Pokrovsk ...",37.840613,0,dead,abramchuk-artem-oleksandrovych-1987-10-18-37-k...
3,Abramchuk,Oleksandrovych,Jurij,28-Jun-83,1.0,"Fedorivka,Vyrivska rural community,Sarny Distr...",Ukraine,Unknown,Unknown,Unknown or no Officer,Unknown or no Officer,Unknown,1-Dec-25,"Myrnohrad, Myrnohradska urban community, Pokro...",42.429345,0,missing,abramchuk-jurij-oleksandrovych-1983-06-28-fedo...
4,Abramchuk,Petrovych,Oleksandr,12-Feb-88,1.0,"Kovel,Kovelska urban community,Kovel District,...",Ukraine,51st separate mechanized brigade<,Mechanized/Infantry,Unknown or no Officer,Unknown or no Officer,Soldier,14-Jul-14,"Cheremshyne, Dovzhanska urban community, Dovzh...",26.418065,0,dead,abramchuk-oleksandr-petrovych-1988-02-12-26-ko...

In [2]:
event2022 = pd.read_csv("data/event_1pd_latest_2022.csv")
event2023 = pd.read_csv("data/event_1pd_latest_2023.csv")
event2024 = pd.read_csv("data/event_1pd_latest_2024.csv")
event2025 = pd.read_csv("data/event_1pd_latest_2025.csv")
event2026 = pd.read_csv("data/event_1pd_latest_2026.csv")
poteru = pd.read_csv("data/poteru_rus.csv")

events = pd.concat(
    [event2022, event2023, event2024, event2025, event2026],
    ignore_index=True
)

events["date"] = pd.to_datetime(
    events["date"].astype(str),
    format="%Y%m%d"
)

events = events.rename(columns={
    "viina_version": "dataset_version",
    "event_id_1pd": "event_id",
    "date": "date",
    "n_reports": "report_count",
    "event_ids": "original_event_ids",
    "sources": "news_sources",

    "geonameid": "location_id",
    "feature_code": "location_type",
    "asciiname": "location_name",
    "ADM1_NAME": "region_name",
    "ADM1_CODE": "region_code",
    "ADM2_NAME": "district_name",
    "ADM2_CODE": "district_code",
    "longitude": "longitude",
    "latitude": "latitude",
    "GEO_PRECISION": "location_precision",

    "t_mil_b": "military_event",
    "a_rus_b": "russian_forces_involved",
    "a_ukr_b": "ukrainian_forces_involved",
    "a_rus_init_b": "russian_forces_initiated",
    "a_ukr_init_b": "ukrainian_forces_initiated",
    "a_civ_b": "civilians_involved",
    "a_other_b": "other_actor_involved",

    "t_aad_b": "air_defense",
    "t_airstrike_b": "airstrike",
    "t_airalert_b": "air_raid_alert",
    "t_uav_b": "drone",
    "t_armor_b": "armored_warfare",
    "t_arrest_b": "arrest_or_detention",
    "t_artillery_b": "artillery",
    "t_control_b": "territorial_control",
    "t_firefight_b": "firefight",
    "t_ied_b": "ied_or_mine",
    "t_raid_b": "raid",
    "t_occupy_b": "occupation",
    "t_property_b": "property_damage",
    "t_cyber_b": "cyber_operation",
    "t_hospital_b": "hospital_or_aid_attack",
    "t_milcas_b": "military_casualties_mentioned",
    "t_civcas_b": "civilian_casualties_mentioned",
    "t_retreat_b": "retreat",
    "t_loc_b": "specific_location_mentioned",
    "t_san_b": "sanctions",

    "tid": "text_id"
})

print(events.shape)
events.head()

C:\Users\lucas\AppData\Local\Temp\ipykernel_14840\1640122038.py:6: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  poteru = pd.read_csv("data/poteru_rus.csv")

(407857, 44)

,dataset_version,event_id,date,report_count,original_event_ids,news_sources,location_id,location_type,location_name,region_name,...,occupation,property_damage,cyber_operation,hospital_or_aid_attack,military_casualties_mentioned,civilian_casualties_mentioned,retreat,specific_location_mentioned,sanctions,text_id
0,bert_20250404023629,181411,2022-02-24,1,2280071,24tvua,705183.0,PPL,Slobozhans'ke,Kharkiv,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,bert_20250404023629,145113,2022-02-24,2,"2279021, 2276365",24tvua,703448.0,PPLC,Kyiv,Kiev City,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,bert_20250404023629,233218,2022-02-24,1,2276366,24tvua,709354.0,PPLA2,Toretsk,Donets'k,...,0,0,0,0,0,0,0,NaN,NaN,NaN
3,bert_20250404023629,173537,2022-02-24,1,2276367,24tvua,704422.0,PPLA2,Pokrovsk,Donets'k,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,bert_20250404023629,88465,2022-02-24,1,2276368,24tvua,698020.0,PPL,Pankivka,Luhans'k,...,0,0,0,0,0,0,0,NaN,NaN,NaN